---

db_name: "blog_analytics"

db_user: "blog_analytics"
db_password: "blabla"
nginx_server_name: "ec2-54-186-52-64.us-west-2.compute.amazonaws.com"
django_settings_file: rocketu_blog_analytics.settings